version: '3.9'

services:
  charity_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      # REDIS_PORT: 6379
  redis:
    image: 'redis'
    volumes:
      - redis_data:/data
volumes:
  redis_data:
